/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.53
 * Generated at: 2021-06-25 06:02:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class freeboardread_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/C:/Users/choi/Desktop/realmovie/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/movie/WEB-INF/lib/spring-security-taglibs-5.0.6.RELEASE.jar!/META-INF/security.tld", Long.valueOf(1528824936000L));
    _jspx_dependants.put("/WEB-INF/lib/spring-security-taglibs-5.0.6.RELEASE.jar", Long.valueOf(1622894647237L));
    _jspx_dependants.put("jar:file:/C:/Users/choi/Desktop/realmovie/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/movie/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1622894594196L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fvar_005fproperty_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fvar_005fproperty_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.release();
    _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fvar_005fproperty_005fnobody.release();
    _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"_csrf\" content=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.token}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("<meta name=\"_csrf_header\" content=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.headerName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\t.row {\r\n");
      out.write("\t\tpadding-left: 5%;\r\n");
      out.write("\t\tpadding-right: 5%;\r\n");
      out.write("\t\tpadding-top: 5%;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.uploadResult {\r\n");
      out.write("\t\twidth:100%;\r\n");
      out.write("\t\tbackground-color: gray;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.uploadResult ul{\r\n");
      out.write("\t\tdisplay:flex;\r\n");
      out.write("\t\tflex-flow: row;\r\n");
      out.write("\t\tjustify-content: center;\r\n");
      out.write("\t\talign-items: center;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.uploadResult ul li {\r\n");
      out.write("\t\tlist-style: none;\r\n");
      out.write("\t\tpadding: 10px;\r\n");
      out.write("\t\talign-content: center;\r\n");
      out.write("\t\ttext-align: center;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.uploadResult ul li img{\r\n");
      out.write("\t\twidth: 100px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.uploadResult ul li span {\r\n");
      out.write("\t\tcolor:white;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.bigPictureWrapper {\r\n");
      out.write("\t\tposition: absolute;\r\n");
      out.write("\t\tdisplay: none;\r\n");
      out.write("\t\tjustify-content: center;\r\n");
      out.write("\t\talign-items: center;\r\n");
      out.write("\t\ttop:0%;\r\n");
      out.write("\t\twidth:100%;\r\n");
      out.write("\t\theight:100%;\r\n");
      out.write("\t\tbackground-color: gray; \r\n");
      out.write("\t\tz-index: 100;\r\n");
      out.write("\t\tbackground:rgba(255,255,255,0.5);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.bigPicture {\r\n");
      out.write("\t\tposition: relative;\r\n");
      out.write("\t\tdisplay:flex;\r\n");
      out.write("\t\tjustify-content: center;\r\n");
      out.write("\t\talign-items: center;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.bigPicture img {\r\n");
      out.write("\t\twidth:600px;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js\"></script>\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/vendor/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/vendor/metisMenu/metisMenu.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/vendor/datatables-plugins/dataTables.bootstrap.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/vendor/datatables-responsive/dataTables.responsive.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/dist/css/sb-admin-2.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/vendor/font-awesome/css/font-awesome.min.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/register.css\">\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/vendor/bootstrap/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/vendor/metisMenu/metisMenu.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/vendor/datatables/js/jquery.dataTables.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/vendor/datatables-plugins/dataTables.bootstrap.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/vendor/datatables-responsive/dataTables.responsive.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/reply.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tfunction replyDel(rno, id) {\r\n");
      out.write("\t\tvar loginId = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mDto.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("\t\tvar articleno = $(\"input[name=artno]\").val();\r\n");
      out.write("\t\tif(loginId == id){\r\n");
      out.write("\t\t\tif(confirm(\"삭제하시겠습니까?\")) {\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tlocation.href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/replies/delete?articleno=\"+articleno+\"&rno=\"+rno;\t\t\t\t\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\talert(\"취소\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\talert(\"작성자만 삭제할 수 있습니다.\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("/* \tfunction replyModify(rno, id) {\r\n");
      out.write("\t\tvar loginId = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mDto.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("\t\tif(loginId == id){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\talert(\"작성자만 수정할 수 있습니다.\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t} */\r\n");
      out.write("\t\r\n");
      out.write("\t$(document).ready(function () {\r\n");
      out.write("\t\t$(\"#modalModify\").on(\"click\", function () {\r\n");
      out.write("\t\t\talert(\"asdf\");\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\tvar operForm = $(\"#operForm\")\r\n");
      out.write("\t\t$(\"button[data-oper = 'list']\").on(\"click\", function (e) {\r\n");
      out.write("\t\t\toperForm.attr(\"action\", \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/board/freeBoard\").submit();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"button[data-oper = 'modify']\").on(\"click\", function () {\r\n");
      out.write("\t\t\toperForm.submit();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar scopeId = document.getElementById(\"scopeId\").value;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar articleno = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${boardList.articleno}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("\t\tvar replyUL = $(\".chat\");\r\n");
      out.write("\t\t  \r\n");
      out.write("\t\tshowList(1);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction showList(page) {\r\n");
      out.write("\t\t\treplyService.getList(\r\n");
      out.write("\t\t\t\t\t{articleno:articleno, contextPath:\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\", page: page || 1 }, \r\n");
      out.write("\t\t\t\t\tfunction(replyCnt, list) {\r\n");
      out.write("\t\t\t\t\t\tif(page == -1){\r\n");
      out.write("\t\t\t\t\t\t\tpageNum = Math.ceil(replyCnt/10.0);\r\n");
      out.write("\t\t\t\t\t\t\tshowList(pageNum);\r\n");
      out.write("\t\t\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t  \r\n");
      out.write("\t\t\t\t\t\tvar str=\"\";\r\n");
      out.write("\t\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t\tif(list == null || list.length == 0){\r\n");
      out.write("\t\t\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tfor (var i = 0, len = list.length || 0; i < len; i++) {\r\n");
      out.write("\t\t\t\t\t\t\tstr +=\"");
      if (_jspx_meth_sec_005fauthentication_005f0(_jspx_page_context))
        return;
      out.write("<li class='left clearfix' data-rno='\"+list[i].rno+\"'>\";\r\n");
      out.write("\t\t\t\t\t\t\tstr +=\"  <div><div class='header'><strong class='primary-font'> \"+list[i].id+\"</strong>&nbsp;&nbsp;<button class='btn btn-danger' type='button'\";\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\tstr\t+=' onclick=\"replyDel('+list[i].rno+', ' + '\\'' + list[i].id +'\\'' + ')\">삭제</button>&nbsp;&nbsp;<button type=\"button\" style=\"display: none;\" data-toggle=\"modal\" data-target=\".bs-example-modal-lg2\" class=\"btn btn-warning\" >수정</button>';\r\n");
      out.write("\t\t\t\t\t\t\tstr +=\"    <small class='pull-right text-muted'>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t+ replyService.displayTime(list[i].updatedate)+\"</small></div>\";\r\n");
      out.write("\t\t\t\t\t\t\tstr +=\"   <p>\"+list[i].replytext+\"</p></div></li>\";\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t\treplyUL.html(str);\r\n");
      out.write("\t\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t\tshowReplyPage(replyCnt);\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t});//end function\r\n");
      out.write("\t\t}//end showList\r\n");
      out.write("\t\t\r\n");
      out.write("\t    var pageNum = 1;\r\n");
      out.write("\t    var replyPageFooter = $(\".panel-footer\");\r\n");
      out.write("\t    \r\n");
      out.write("\t    function showReplyPage(replyCnt) {\r\n");
      out.write("\t    \tvar endNum = Math.ceil(pageNum / 10.0) * 10;\r\n");
      out.write("\t    \tvar startNum = endNum - 9;\r\n");
      out.write("\t    \t\r\n");
      out.write("\t    \tvar prev = startNum != 1;\r\n");
      out.write("\t    \tvar next = false;\r\n");
      out.write("\t    \t\r\n");
      out.write("\t    \tif(endNum * 10 >= replyCnt) {\r\n");
      out.write("\t    \t\tendNum = Math.ceil(replyCnt/10.0);\r\n");
      out.write("\t    \t}\r\n");
      out.write("\t    \t\r\n");
      out.write("\t    \tif(endNum * 10 < replyCnt) {\r\n");
      out.write("\t    \t\tnext = true;\r\n");
      out.write("\t    \t}\r\n");
      out.write("\t    \t\r\n");
      out.write("\t    \tvar str = \"<ul class='pagination pull-right'>\";\r\n");
      out.write("\t    \t\r\n");
      out.write("\t    \tif(prev) {\r\n");
      out.write("\t    \t\tstr+= \"<li class='page-item'><a class='page-link' href='\"+(startNum -1)+\"'>Previous</a></li>\";\r\n");
      out.write("\t    \t}\r\n");
      out.write("\t    \t\r\n");
      out.write("\t    \tfor(var i = startNum ; i <= endNum; i++) {\r\n");
      out.write("\t    \t\tvar active = pageNum == i? \"active\":\"\";\r\n");
      out.write("\t    \t\t\r\n");
      out.write("\t    \t\tstr+= \"<li class='page-item \"+active+\" '><a class='page-link' href='\"+i+\"'>\"+i+\"</a></li>\";\r\n");
      out.write("\t    \t}\r\n");
      out.write("\t    \t\r\n");
      out.write("\t    \tif(next) {\r\n");
      out.write("\t    \t\tstr+= \"<li class='page-item'><a class='page-link' href='\"+(endNum + 1)+\"'>Next</a></li>\";\r\n");
      out.write("\t    \t}\r\n");
      out.write("\t    \t\r\n");
      out.write("\t    \tstr += \"</ul></div>\";\r\n");
      out.write("\t    \t\r\n");
      out.write("\t    \treplyPageFooter.html(str);\r\n");
      out.write("\t    }\r\n");
      out.write("\t     \r\n");
      out.write("\t    replyPageFooter.on(\"click\",\"li a\", function(e) {\r\n");
      out.write("\t    \te.preventDefault();\r\n");
      out.write("\t    \tconsole.log(\"page click\");\r\n");
      out.write("\t    \t\r\n");
      out.write("\t    \tvar targetPageNum = $(this).attr(\"href\");\r\n");
      out.write("\t    \t\r\n");
      out.write("\t    \tconsole.log(\"targetPageNum: \" + targetPageNum);\r\n");
      out.write("\t    \t\r\n");
      out.write("\t    \tpageNum = targetPageNum;\r\n");
      out.write("\t    \t\r\n");
      out.write("\t    \tshowList(pageNum);\r\n");
      out.write("\t     });     \r\n");
      out.write("\t\t\r\n");
      out.write("\t    var modal = $(\".modal\");\r\n");
      out.write("\t    var modalInputReplyText = modal.find(\"input[name='replytext']\");\r\n");
      out.write("\t    var modalInputReplyer = modal.find(\"input[name='replyer']\");\r\n");
      out.write("\t    var modalInputReplyDate = modal.find(\"input[name='replyDate']\");\r\n");
      out.write("\t    \r\n");
      out.write("\t    var modalModifyBtn = $(\"#modalModifyBtn\");\r\n");
      out.write("\t    var modalRemoveBtn = $(\"#modalRemoveBtn\");\r\n");
      out.write("\t    var modalRegisterBtn = $(\"#modalRegisterBtn\");\r\n");
      out.write("\t    \r\n");
      out.write("\t    $(\"#modalCloseBtn\").on(\"click\", function(e){\r\n");
      out.write("\t    \tmodal.modal(\"hide\");\r\n");
      out.write("\t    });\r\n");
      out.write("\t    $(\"#modalCloseBtn1\").on(\"click\", function(e){\r\n");
      out.write("\t    \tmodal.modal(\"hide\");\r\n");
      out.write("\t    });\r\n");
      out.write("\t    \r\n");
      out.write("\t    $(\"#addReplyBtn\").on(\"click\", function(e){\r\n");
      out.write("\t    \tmodalInputReplyDate.closest(\"div\").hide();\r\n");
      out.write("\t    \tmodal.find(\"button[id !='modalCloseBtn']\").hide();\r\n");
      out.write("\t    \t\r\n");
      out.write("\t    \tmodalRegisterBtn.show();\r\n");
      out.write("\t    \t\r\n");
      out.write("\t    \t$(\".modal\").modal(\"show\");\r\n");
      out.write("\t    });\r\n");
      out.write("\t    \r\n");
      out.write("\t    // 새로운 댓글 처리\r\n");
      out.write("\t    modalRegisterBtn.on(\"click\", function(e) {\r\n");
      out.write("\t    \tvar replytext = $(\"input[name='replytext']\").val();\r\n");
      out.write("\t    \tvar id = $(\"input[name='replyId']\").val();\r\n");
      out.write("\t    \tvar reply = {\r\n");
      out.write("\t    \t\t\treplytext: replytext,\r\n");
      out.write("\t    \t\t\tid:id,\r\n");
      out.write("\t    \t\t\tcontextPath:\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\",\r\n");
      out.write("\t    \t\t\tarticleno:articleno\r\n");
      out.write("\t    \t\t};\r\n");
      out.write("\t        replyService.add(reply, function(){\r\n");
      out.write("\t        \t\r\n");
      out.write("\t        \tmodal.find(\"input[name='replytext']\").val(\"\");\r\n");
      out.write("\t        \tmodal.modal(\"hide\"); \r\n");
      out.write("\t        \t\r\n");
      out.write("\t        \tshowList(-1);\r\n");
      out.write("\t        });\r\n");
      out.write("\t\t});\r\n");
      out.write("\t    \r\n");
      out.write("\t    modalModifyBtn.on(\"click\", function(e){\r\n");
      out.write("\t    \tvar reply = {\r\n");
      out.write("\t    \t\t\trno:modal.data(\"rno\"), \r\n");
      out.write("\t    \t\t\treplytext: modalInputReplyText.val(),\r\n");
      out.write("\t    \t\t\tcontextPath:\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\r\n");
      out.write("\t    \t\t};\r\n");
      out.write("\t    \t\r\n");
      out.write("\t    \treplyService.update(reply, function(result) {\r\n");
      out.write("\t    \t\talert(result);\r\n");
      out.write("\t    \t\t\r\n");
      out.write("\t     \t    modal.modal(\"hide\");\r\n");
      out.write("\t     \t    showList(pageNum);\r\n");
      out.write("\t     \t});\r\n");
      out.write("\t    });\r\n");
      out.write("\r\n");
      out.write("\t    modalRemoveBtn.on(\"click\", function (e) {\r\n");
      out.write("\t    \tvar reply = {\r\n");
      out.write("\t    \t\t\trno : modal.data(\"rno\"), \r\n");
      out.write("\t    \t\t\tcontextPath:\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\r\n");
      out.write("\t    \t\t};\r\n");
      out.write("\t    \t\r\n");
      out.write("\t    \treplyService.remove(reply, function(result) {\r\n");
      out.write("\t    \t\talert(result);\r\n");
      out.write("\t    \t\t\r\n");
      out.write("\t    \t\tmodal.modal(\"hide\");\r\n");
      out.write("\t    \t\tshowList(pageNum);\r\n");
      out.write("\t    \t});\r\n");
      out.write("\t    });\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(document).ready(function() {\r\n");
      out.write("\tvar operForm = $(\"#operForm\"); \r\n");
      out.write("\t\t$(\"button[data-oper='modify']\").on(\"click\", function(e){\r\n");
      out.write("\t  \toperForm.attr(\"action\",\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/board/freeboardmodify\").submit();\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"button[data-oper='list']\").on(\"click\", function(e){\r\n");
      out.write("\t\toperForm.find(\"#articleno\").remove();\r\n");
      out.write("\t\toperForm.attr(\"action\",\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/board/freeBoard\")\r\n");
      out.write("\t\toperForm.submit();\r\n");
      out.write("\t});\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("$(document).ready(function() {\r\n");
      out.write("\t  (function() {\r\n");
      out.write("\t  \tvar articleno = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${boardList.articleno}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("\t    \r\n");
      out.write("\t    $.getJSON(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/board/getAttachList\", {articleno: articleno}, function(arr) {\r\n");
      out.write("\t        \r\n");
      out.write("\t       console.log(\"arr test\"+arr);\r\n");
      out.write("\t       \r\n");
      out.write("\t       var str = \"\";\r\n");
      out.write("\t       \r\n");
      out.write("\t       $(arr).each(function(i, attach){\r\n");
      out.write("\t       \r\n");
      out.write("\t         if(attach.filetype){\r\n");
      out.write("\t           var fileCallPath =  encodeURIComponent(attach.uploadPath+ \"/s_\" + attach.uuid +\"_\" + attach.fileName);\r\n");
      out.write("\t           \r\n");
      out.write("\t           str += \"<li data-path='\" + attach.uploadPath + \"' data-uuid='\" + attach.uuid + \"' data-filename='\" + attach.fileName + \"' data-type='\" + attach.filetype + \"' ><div>\";\r\n");
      out.write("\t           str += \"<img src='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/upload/display?fileName=\" + fileCallPath+\"'>\";\r\n");
      out.write("\t           str += \"</div>\";\r\n");
      out.write("\t           str +\"</li>\";\r\n");
      out.write("\t         } else {\r\n");
      out.write("\t           str += \"<li data-path='\" + attach.uploadPath + \"' data-uuid='\" + attach.uuid + \"' data-filename='\" + attach.fileName + \"' data-type='\" + attach.filetype+\"' ><div>\";\r\n");
      out.write("\t           str += \"<span> \"+ attach.fileName + \"</span><br/>\";\r\n");
      out.write("\t           str += \"<img src='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/image/thumbnail.jpg'style='cursor: pointer;'></a>\";\r\n");
      out.write("\t           str += \"</div>\";\r\n");
      out.write("\t           str +\"</li>\";\r\n");
      out.write("\t         }\r\n");
      out.write("\t       });\r\n");
      out.write("\t       \r\n");
      out.write("\t       $(\".uploadResult ul\").html(str);\r\n");
      out.write("\t     });//end getjson\r\n");
      out.write("\t  })();//end function\r\n");
      out.write("\t  \r\n");
      out.write("\t  $(\".uploadResult\").on(\"click\",\"li\", function(e){\r\n");
      out.write("\t      \r\n");
      out.write("\t    console.log(\"view image\");\r\n");
      out.write("\t    \r\n");
      out.write("\t    var liObj = $(this);\r\n");
      out.write("\t    \r\n");
      out.write("\t    var path = encodeURIComponent(liObj.data(\"path\")+\"/\" + liObj.data(\"uuid\")+\"_\" + liObj.data(\"filename\"));\r\n");
      out.write("\r\n");
      out.write("\t    if(liObj.data(\"type\")){\r\n");
      out.write("\t      showImage(path.replace(new RegExp(/\\\\/g),\"/\"));\r\n");
      out.write("\t    } else {\r\n");
      out.write("\t      self.location =\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/upload/download?fileName=\" + path;\r\n");
      out.write("\t    }\r\n");
      out.write("\t    \r\n");
      out.write("\t    \r\n");
      out.write("\t  });\r\n");
      out.write("\t  \r\n");
      out.write("\t  function showImage(fileCallPath){\r\n");
      out.write("\t    $(\".bigPictureWrapper\").css(\"display\",\"flex\").show();\r\n");
      out.write("\t    \r\n");
      out.write("\t    $(\".bigPicture\")\r\n");
      out.write("\t    .html(\"<img src='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/upload/display?fileName=\"+fileCallPath+\"' >\")\r\n");
      out.write("\t    .animate({width:\"100%\", height: \"100%\"}, 1000);\r\n");
      out.write("\t    \r\n");
      out.write("\t  }\r\n");
      out.write("\r\n");
      out.write("\t  $(\".bigPictureWrapper\").on(\"click\", function(e){\r\n");
      out.write("\t    $(\".bigPicture\").animate({width:\"0%\", height: \"0%\"}, 1000);\r\n");
      out.write("\t    setTimeout(function(){\r\n");
      out.write("\t      $(\".bigPictureWrapper\").hide();\r\n");
      out.write("\t    }, 1000);\r\n");
      out.write("\t  });\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("  <div class=\"col-lg-12\">\r\n");
      out.write("    <div class=\"panel panel-default\" >\r\n");
      out.write("      <!-- /.panel-heading -->\r\n");
      out.write("      <div class=\"panel-body\">\r\n");
      out.write("        <!-- <form role=\"form\" action=\"/board/register\" method=\"post\"> -->\r\n");
      out.write("          <div class=\"form-group\">\r\n");
      out.write("            <label>Articleno</label> <input class=\"form-control\" name='articleno' value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${boardList.articleno }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" disabled=\"disabled\">\r\n");
      out.write("            <input type=\"hidden\" name='artno' value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${boardList.articleno }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"form-group\">\r\n");
      out.write("            <label>Subject</label> <input class=\"form-control\" name='title' value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${boardList.title }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" disabled=\"disabled\">\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"form-group\">\r\n");
      out.write("            <label>Content</label>\r\n");
      out.write("            <textarea class=\"form-control\" rows=\"3\" name='content' disabled=\"disabled\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${boardList.content }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</textarea>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"form-group\">\r\n");
      out.write("            <label>ID</label> <input class=\"form-control\" name='id' value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${boardList.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" disabled=\"disabled\">\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"form-group\">\r\n");
      out.write("            <label>RegDate</label> <input class=\"form-control\" name='regdate' value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${boardList.regdate }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" disabled=\"disabled\">\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"form-group\" style=\"margin: 0 auto; text-align: center;\">\r\n");
      out.write("          ");
      if (_jspx_meth_sec_005fauthentication_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("          \t");
      if (_jspx_meth_sec_005fauthorize_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t          <button data-oper=\"list\" class=\"btn btn-default\" style=\"border: 1px solid #000000;\">List</button>\r\n");
      out.write("          </div>\r\n");
      out.write("          <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/board/modify\" method=\"get\" id=\"operForm\">\r\n");
      out.write("          \t<input type=\"hidden\" id=\"articleno\" name=\"articleno\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${boardList.articleno}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("          \t<input type=\"hidden\" id=\"pageNum\" name=\"pageNum\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cri.pageNum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("          \t<input type=\"hidden\" id=\"type\" name=\"type\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cri.type}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("          \t<input type=\"hidden\" id=\"keyword\" name=\"keyword\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cri.keyword}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("          \t<input type=\"hidden\" id=\"scopeId\" name=\"scopeId\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.mDto.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("          </form>\r\n");
      out.write("        <!-- </form> -->\r\n");
      out.write("      </div>\r\n");
      out.write("      <!--  end panel-body -->\r\n");
      out.write("    </div>\r\n");
      out.write("    <!--  end panel-body -->\r\n");
      out.write("  </div>\r\n");
      out.write("  <!-- end panel -->\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class='bigPictureWrapper'>\r\n");
      out.write("  <div class='bigPicture'>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("  <div class=\"col-lg-12\">\r\n");
      out.write("    <div class=\"panel panel-default\">\r\n");
      out.write("\r\n");
      out.write("      <div class=\"panel-heading\">Files</div>\r\n");
      out.write("      <!-- /.panel-heading -->\r\n");
      out.write("      <div class=\"panel-body\">\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"uploadResult\"> \r\n");
      out.write("          <ul>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <!--  end panel-body -->\r\n");
      out.write("    </div>\r\n");
      out.write("    <!--  end panel-body -->\r\n");
      out.write("  </div>\r\n");
      out.write("  <!-- end panel -->\r\n");
      out.write("</div>\r\n");
      out.write("<!-- /.row -->\r\n");
      out.write("<div class='row'>\r\n");
      out.write("  <div class=\"col-lg-12\">\r\n");
      out.write("    <!-- /.panel -->\r\n");
      out.write("    <div class=\"panel panel-default\">\r\n");
      out.write("      <div class=\"panel-heading\">\r\n");
      out.write("        <i class=\"fa fa-comments fa-fw\"></i> Reply\r\n");
      out.write("        ");
      if (_jspx_meth_sec_005fauthorize_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("        ");
      if (_jspx_meth_sec_005fauthorize_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("      </div>      \r\n");
      out.write("      \r\n");
      out.write("      <!-- /.panel-heading -->\r\n");
      out.write("      <div class=\"panel-body\">        \r\n");
      out.write("        <ul class=\"chat\">\r\n");
      out.write("        </ul>\r\n");
      out.write("        <!-- ./ end ul -->\r\n");
      out.write("      </div>\r\n");
      out.write("      <!-- /.panel .chat-panel -->\r\n");
      out.write("\r\n");
      out.write("\t  <div class=\"panel-footer\"></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <!-- ./ end row -->\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"modal fade bs-example-modal-lg\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"myLargeModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("  <div class=\"modal-dialog modal-lg\">\r\n");
      out.write("    <div class=\"modal-content\">\r\n");
      out.write("      <div class=\"modal-body\">\r\n");
      out.write("            \t<div class=\"form-group\">\r\n");
      out.write("            \t\t<label>댓글내용</label>\r\n");
      out.write("            \t\t<input class=\"form-control\" name=\"replytext\" placeholder=\"댓글을 작성해주세요\">\r\n");
      out.write("            \t</div>\r\n");
      out.write("            \t<div class=\"form-group\">\r\n");
      out.write("            \t\t<label>작성자</label>\r\n");
      out.write("            \t\t<input class=\"form-control\" name=\"replyId\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.mDto.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly=\"readonly\">\r\n");
      out.write("            \t</div>\r\n");
      out.write("            </div>\r\n");
      out.write("\t\t\t<div class=\"modal-footer\">\r\n");
      out.write("        \t\t<button id=\"modalRegisterBtn\" type=\"button\" class=\"btn btn-primary\">Register</button>\r\n");
      out.write("        \t\t<button id=\"modalCloseBtn\" type=\"button\" class=\"btn btn-default\">Close</button>\r\n");
      out.write("      \t\t</div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"modal fade bs-example-modal-lg2\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"myLargeModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("  <div class=\"modal-dialog modal-lg\">\r\n");
      out.write("    <div class=\"modal-content\">\r\n");
      out.write("      <div class=\"modal-body\">\r\n");
      out.write("            \t<div class=\"form-group\">\r\n");
      out.write("            \t\t<label>댓글내용</label>\r\n");
      out.write("            \t\t<input class=\"form-control\" name=\"replyModifyText\" value=\"\">\r\n");
      out.write("            \t</div>\r\n");
      out.write("            \t<div class=\"form-group\">\r\n");
      out.write("            \t\t<label>작성자</label>\r\n");
      out.write("            \t\t<input class=\"form-control\" name=\"replyId\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.mDto.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly=\"readonly\">\r\n");
      out.write("            \t</div>\r\n");
      out.write("            </div>\r\n");
      out.write("\t\t\t<div class=\"modal-footer\">\r\n");
      out.write("        \t\t<button id=\"modalRegisterBtn1\" type=\"button\" class=\"btn btn-primary\">Register</button>\r\n");
      out.write("        \t\t<button id=\"modalCloseBtn1\" type=\"button\" class=\"btn btn-default\">Close</button>\r\n");
      out.write("      \t\t</div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/board/freeboardread.jsp(5,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("ctx");
      // /WEB-INF/views/board/freeboardread.jsp(5,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/board/freeboardread.jsp(5,0) '${pageContext.request.contextPath == '/' ? '' : pageContext.request.contextPath }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath == '/' ? '' : pageContext.request.contextPath }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/views/board/freeboardread.jsp(5,0) name = scope type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setScope("application");
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_sec_005fauthentication_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sec:authentication
    org.springframework.security.taglibs.authz.AuthenticationTag _jspx_th_sec_005fauthentication_005f0 = (org.springframework.security.taglibs.authz.AuthenticationTag) _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fvar_005fproperty_005fnobody.get(org.springframework.security.taglibs.authz.AuthenticationTag.class);
    boolean _jspx_th_sec_005fauthentication_005f0_reused = false;
    try {
      _jspx_th_sec_005fauthentication_005f0.setPageContext(_jspx_page_context);
      _jspx_th_sec_005fauthentication_005f0.setParent(null);
      // /WEB-INF/views/board/freeboardread.jsp(147,14) name = property type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sec_005fauthentication_005f0.setProperty("principal");
      // /WEB-INF/views/board/freeboardread.jsp(147,14) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sec_005fauthentication_005f0.setVar("sec");
      int _jspx_eval_sec_005fauthentication_005f0 = _jspx_th_sec_005fauthentication_005f0.doStartTag();
      if (_jspx_th_sec_005fauthentication_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fvar_005fproperty_005fnobody.reuse(_jspx_th_sec_005fauthentication_005f0);
      _jspx_th_sec_005fauthentication_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sec_005fauthentication_005f0, _jsp_getInstanceManager(), _jspx_th_sec_005fauthentication_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_sec_005fauthentication_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sec:authentication
    org.springframework.security.taglibs.authz.AuthenticationTag _jspx_th_sec_005fauthentication_005f1 = (org.springframework.security.taglibs.authz.AuthenticationTag) _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fvar_005fproperty_005fnobody.get(org.springframework.security.taglibs.authz.AuthenticationTag.class);
    boolean _jspx_th_sec_005fauthentication_005f1_reused = false;
    try {
      _jspx_th_sec_005fauthentication_005f1.setPageContext(_jspx_page_context);
      _jspx_th_sec_005fauthentication_005f1.setParent(null);
      // /WEB-INF/views/board/freeboardread.jsp(399,10) name = property type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sec_005fauthentication_005f1.setProperty("principal");
      // /WEB-INF/views/board/freeboardread.jsp(399,10) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sec_005fauthentication_005f1.setVar("sec");
      int _jspx_eval_sec_005fauthentication_005f1 = _jspx_th_sec_005fauthentication_005f1.doStartTag();
      if (_jspx_th_sec_005fauthentication_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fvar_005fproperty_005fnobody.reuse(_jspx_th_sec_005fauthentication_005f1);
      _jspx_th_sec_005fauthentication_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sec_005fauthentication_005f1, _jsp_getInstanceManager(), _jspx_th_sec_005fauthentication_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_sec_005fauthorize_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sec:authorize
    org.springframework.security.taglibs.authz.JspAuthorizeTag _jspx_th_sec_005fauthorize_005f0 = (org.springframework.security.taglibs.authz.JspAuthorizeTag) _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.get(org.springframework.security.taglibs.authz.JspAuthorizeTag.class);
    boolean _jspx_th_sec_005fauthorize_005f0_reused = false;
    try {
      _jspx_th_sec_005fauthorize_005f0.setPageContext(_jspx_page_context);
      _jspx_th_sec_005fauthorize_005f0.setParent(null);
      // /WEB-INF/views/board/freeboardread.jsp(400,11) name = access type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sec_005fauthorize_005f0.setAccess("isAuthenticated()");
      int _jspx_eval_sec_005fauthorize_005f0 = _jspx_th_sec_005fauthorize_005f0.doStartTag();
      if (_jspx_eval_sec_005fauthorize_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        out.write("\r\n");
        out.write("          \t\t");
        if (_jspx_meth_c_005fif_005f0(_jspx_th_sec_005fauthorize_005f0, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("          \t");
      }
      if (_jspx_th_sec_005fauthorize_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.reuse(_jspx_th_sec_005fauthorize_005f0);
      _jspx_th_sec_005fauthorize_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sec_005fauthorize_005f0, _jsp_getInstanceManager(), _jspx_th_sec_005fauthorize_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_sec_005fauthorize_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_sec_005fauthorize_005f0);
      // /WEB-INF/views/board/freeboardread.jsp(401,12) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sec.username eq boardList.id}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t          <button class=\"btn btn-primary\" data-oper=\"modify\" id=\"modify\">Modify</button>\r\n");
          out.write("          \t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_sec_005fauthorize_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sec:authorize
    org.springframework.security.taglibs.authz.JspAuthorizeTag _jspx_th_sec_005fauthorize_005f1 = (org.springframework.security.taglibs.authz.JspAuthorizeTag) _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.get(org.springframework.security.taglibs.authz.JspAuthorizeTag.class);
    boolean _jspx_th_sec_005fauthorize_005f1_reused = false;
    try {
      _jspx_th_sec_005fauthorize_005f1.setPageContext(_jspx_page_context);
      _jspx_th_sec_005fauthorize_005f1.setParent(null);
      // /WEB-INF/views/board/freeboardread.jsp(454,8) name = access type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sec_005fauthorize_005f1.setAccess("hasRole('ROLE_MEMBER')");
      int _jspx_eval_sec_005fauthorize_005f1 = _jspx_th_sec_005fauthorize_005f1.doStartTag();
      if (_jspx_eval_sec_005fauthorize_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        out.write("\r\n");
        out.write("\t        <!-- <button id='addReplyBtn' class='btn btn-primary btn-xs pull-right'>New Reply</button> -->\r\n");
        out.write("\t        <button type=\"button\" class=\"btn btn-primary btn-xs pull-right\" data-toggle=\"modal\" data-target=\".bs-example-modal-lg\">댓글작성</button>\r\n");
        out.write("        ");
      }
      if (_jspx_th_sec_005fauthorize_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.reuse(_jspx_th_sec_005fauthorize_005f1);
      _jspx_th_sec_005fauthorize_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sec_005fauthorize_005f1, _jsp_getInstanceManager(), _jspx_th_sec_005fauthorize_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_sec_005fauthorize_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sec:authorize
    org.springframework.security.taglibs.authz.JspAuthorizeTag _jspx_th_sec_005fauthorize_005f2 = (org.springframework.security.taglibs.authz.JspAuthorizeTag) _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.get(org.springframework.security.taglibs.authz.JspAuthorizeTag.class);
    boolean _jspx_th_sec_005fauthorize_005f2_reused = false;
    try {
      _jspx_th_sec_005fauthorize_005f2.setPageContext(_jspx_page_context);
      _jspx_th_sec_005fauthorize_005f2.setParent(null);
      // /WEB-INF/views/board/freeboardread.jsp(458,8) name = access type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sec_005fauthorize_005f2.setAccess("isAnonymous()");
      int _jspx_eval_sec_005fauthorize_005f2 = _jspx_th_sec_005fauthorize_005f2.doStartTag();
      if (_jspx_eval_sec_005fauthorize_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        out.write("\r\n");
        out.write("\t        <button type=\"button\" class=\"btn btn-primary btn-xs pull-right\">로그인이 필요한 기능입니다.</button>\r\n");
        out.write("        ");
      }
      if (_jspx_th_sec_005fauthorize_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.reuse(_jspx_th_sec_005fauthorize_005f2);
      _jspx_th_sec_005fauthorize_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sec_005fauthorize_005f2, _jsp_getInstanceManager(), _jspx_th_sec_005fauthorize_005f2_reused);
    }
    return false;
  }
}
